services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: clavis-php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - PHP_MEMORY_LIMIT=512M
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_START_WITH_REQUEST=yes
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - clavis-network

  mysql:
    image: mysql:8.0
    container_name: clavis-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: clavis_db
      MYSQL_USER: clavis_user
      MYSQL_PASSWORD: clavis_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./clavis_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clavis-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: clavis-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - clavis-network

networks:
  clavis-network:
    driver: bridge

volumes:
  mysql_data: